services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mogul'
      - 'POSTGRES_PASSWORD=mogul'
      - 'POSTGRES_USER=mogul'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=mogul'
      - 'RABBITMQ_DEFAULT_USER=mogul'
    ports:
      - '5672:5672'
